# Generated by Django 5.2.8 on 2025-12-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento (Bs)')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Límite de usos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Veces usado')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Expiración')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.coupon'),
        ),
    ]
