# Generated by Django 5.2.8 on 2025-12-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_coupon_sale_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección Física')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detalles de la casa/referencias')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Asignación'), ('ASSIGNED', 'Asignado a Repartidor'), ('IN_TRANSIT', 'En Camino'), ('DELIVERED', 'Entregado'), ('FAILED', 'No se pudo entregar')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_note', to='sales.sale')),
            ],
        ),
    ]
