# Generated by Django 5.2.8 on 2025-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Cliente'), ('EMPLOYEE', 'Trabajador'), ('DELIVERY', 'Delivery')], default='CUSTOMER', max_length=10, verbose_name='Rol de Usuario'),
        ),
    ]
